### ISSUE TITLE
New user issues

### ISSUE THREAD

**Issue by amanda07w** [Rappsilber-Laboratory/build_xiview#89]
Dear Colin,

I have just discovered this useful tool! But am having trouble on a few things..

When trying to load a PDB file I get a message saying "No sequence matches found between this search and the PDB file. Please check the PDB file or code is correct." I think this is because my file has no sequence. How do I add other metadata such as the sequence not just the crosslink sequences? Should I have a separate file?
![image](https://user-images.githubusercontent.com/103261477/162441326-e08572b6-95ec-467b-90be-fca16f4a8a43.png)

Secondly, I tried to follow these steps to add annotations but I must be doing it wrong (https://xiview.org/xidocs/html/import/userannotations.html) - can you help?
[08Mar2022 Results HSA_CSVwithoutpeaklists.csv](https://github.com/Rappsilber-Laboratory/xiView_container/files/8452125/08Mar2022.Results.HSA_CSVwithoutpeaklists.csv)
[08Mar2022 Results HSA_MinimalCSV.csv](https://github.com/Rappsilber-Laboratory/xiView_container/files/8452128/08Mar2022.Results.HSA_MinimalCSV.csv)

Thanks so much!
Amanda

**Comment by colin-combe** [comment]
Hi,

> I think this is because my file has no sequence.

Yes, that would be right. If you are uploading your data as a CSV file then you can upload a FASTA file alongside it containing the sequences. The sequences from the FASTA file should be used if the id's match up with those used in the CSV file (it takes the id in the fasta file header to be after '>' up to the first space).

If you're uploading your data as an mzIdentML then you could include the sequences in the mzIdentml file. You should be able to upload a FASTA file alongside an mzIdentML file without sequences and get it to use sequences from the FASTA file, but this is currently broken. (I.e. for mzIdentML files only option is currently to include sequences in mzIdentML file.)

Also, if you use valid uniprot accession numbers as the protein id's then it _should_ get the sequences for you if they are missing. I see you do have a valid looking accession in the CSV files you posted and it's not working for you. I think that's maybe because you've used an accession for something that's only in trembl, it only uses the reviewed uniprot database for this. Maybe you could change the accession used.

Re. the annotations - these are annotations of the protein sequence, it possibly isn't working because the sequences are missing, though actually i think it should still draw something. Lets come back to that when the sequences are fixed,

cheers,
colin
